name: Publish NuGet Package

on:
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release
        
      - name: Determine project name
        id: project_name
        run: |
          csproj_file=$(find . -name '*.csproj' -print -quit)
          project_name=$(basename "$csproj_file" .csproj)
          echo "::set-output name=name::$project_name"
        
      - name: Determine version
        id: version
        run: |
          version=$(dotnet project-file-name ${GITHUB_WORKSPACE}/${{ steps.project_name.outputs.name }}.csproj --version)
          version=$(echo "${version}" | tr -d '[:space:]')
          echo "::set-output name=version::$version"
      
      - name: Pack
        run: |
          base_version="${{ steps.version.outputs.version }}"
          version="${base_version}-dev0.$((${GITHUB_RUN_NUMBER} / 100)).$((${GITHUB_RUN_NUMBER} % 100))"
          dotnet pack --configuration Release /p:Version=$version --output nupkgs
          
      - name: Publish to NuGet
        run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
