name: Dev Test

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build and test
      run: dotnet build --configuration Release && dotnet test --no-build --verbosity normal
